[package]
name = "dball-combora"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
anyhow = "1"
ansi_term = "0.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[lints]
workspace = true
