[package]
name = "dball-client"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite", "chrono"] }
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"

[lints]
workspace = true
